name: DevOps Final Project CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Show Docker images
        run: docker images

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Test Ansible connection
        env:
          EC2_HOST: ${{ vars.EC2_HOST }}
        run: |
          ansible all \
            -i "$EC2_HOST," \
            -u ec2-user \
            --private-key ec2_key.pem \
            -m ping \
            -o
